### ISSUE TITLE
No data received after connection

### ISSUE THREAD

**Issue by Kallyfr** [cyrilpawelko/arkteos_reg3#1]
Hello,

I tried the script but after connecting, no data received :
python pac.py
Connection to 192.168.100.185:9641 successfull.

^CReceived 0 octets
Traceback (most recent call last):
  File "pac.py", line 65, in <module>
    data_lenght = len(data)
NameError: name 'data' is not defined

Any idea ?

thanks

**Comment by cyrilpawelko** [comment]
Hello,

What is your heat pump model ?
Do you know wheter it is a REG II or REG III model ?
A telnet on port 9641 should send some (garbage) data

**Comment by skyw43** [comment]
Very impressive work ! But same issue on my side, data is empty. It seems I use REG2, almost sure. When I use Wireshark to snif traffic between REG2 and java applet running my laptop, I see in the sniffed packets three data sets pushed using TCP protocol from REG2 IP address, data size is 156 bytes, then 150 bytes, then 83 bytes, all separated from 1 second then cycling again and again, only when java applet is fully loaded and stays on entry screen with  floor temp, ECS temp, pressure, outside temp, etc. Will try to dig further into data sets to find some logic based on your reverse engineering

**Comment by cyrilpawelko** [comment]
Hello,
Thanks for your feedback.
I guess REG2 and REG3 are different : the java REG2 app cannot connect to my REG3 (furthermore, TCP ports used are different).
Anyway, I guess the protocols are very similar.
A quick hint to identify "Consigne Z1" value : on my REG3, it is set to zero when heat is turned off.
